[mcp_servers.ai-game-developer]
enabled = true
http_headers = { "Authorization" = "Bearer agd_pk_a7OIo_B7a6ykMvR6YNqhJoVdEK0_4jNh2j294Z5rm6c" }
startup_timeout_sec = 30
tool_timeout_sec = 300
url = "https://ai-game.dev/mcp/p/4f0f22db"

[mcp_servers.ai-game-developer.tools.script-execute]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.tests-run]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.assets-refresh]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-create]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-modify]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.assets-prefab-create]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.assets-prefab-open]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-component-add]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-component-modify]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.assets-prefab-save]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.assets-prefab-close]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.scene-save]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-destroy]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.object-modify]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.assets-modify]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.console-clear-logs]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.select_engine_instance]
approval_mode = "approve"
